// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EntityFrameworkExample.Models;

public partial class Book
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Author { get; set; }

    public DateTime PublishedDate { get; set; }

    public string PublisherNmae { get; set; }
}