// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EntityFrameworkExample.Models;

public partial class FirstEFDemoContext : DbContext
{
    public FirstEFDemoContext(DbContextOptions<FirstEFDemoContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Author> Authors { get; set; }

    public virtual DbSet<Book> Books { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Author>(entity =>
        {
            entity.Property(e => e.Adress)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.ImageLink)
                .IsRequired()
                .HasDefaultValue("");
            entity.Property(e => e.Name).IsRequired();
        });

        modelBuilder.Entity<Book>(entity =>
        {
            entity.Property(e => e.Author).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.PublisherNmae).HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}